CI: Modify regex
The out of the test `test_panic_raw_ctx_should_terminate_abnormally`
seems to have changed with a recent update of `cargo` causing our `grep`
call to fail.

The error now looks like
```
thread 'tests::test_panic_raw_ctx_should_terminate_abnormally' panicked at secp256k1-sys/src/lib.rs:904:5:
[libsecp256k1] illegal argument.
!rustsecp256k1_v0_8_1_fe_is_zero(&ge->x)
```

Based solely on this output and the fact that our `grep` statement used
to work I conclude that the output now includes new line information.

Modify the regex to do non-greedy comparison against everything before
the `[libsecp256k1]` bit.